// <auto-generated />
using HotelListing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelListing.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220313061930_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelListing.Data.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "India",
                            ShortName = "IND"
                        },
                        new
                        {
                            CountryId = 2,
                            Name = "United States",
                            ShortName = "USA"
                        },
                        new
                        {
                            CountryId = 3,
                            Name = "Canada",
                            ShortName = "CAN"
                        },
                        new
                        {
                            CountryId = 4,
                            Name = "Italy",
                            ShortName = "ITL"
                        });
                });

            modelBuilder.Entity("HotelListing.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Address = "Phase-11 India",
                            CountryId = 1,
                            Name = "Indian Hotel",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 15,
                            Address = "Phase-11 India",
                            CountryId = 1,
                            Name = "Indian Hotel-2",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 12,
                            Address = "Phase-12 United",
                            CountryId = 2,
                            Name = "United Hotel",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 13,
                            Address = "Phase-13 Canada",
                            CountryId = 3,
                            Name = "Canada Hotel",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 14,
                            Address = "Phase-14 Italy",
                            CountryId = 4,
                            Name = "Italy Hotel",
                            Rating = 5.0
                        });
                });

            modelBuilder.Entity("HotelListing.Data.Hotel", b =>
                {
                    b.HasOne("HotelListing.Data.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
